In [1]:
import numpy as np

In [2]:
a = np.array(4)
a

array(4)

In [4]:
a.ndim

0

In [13]:
mat = np.array([[1,2,3],[4,5,6],[4,5,0]])
print(mat)
# Shape of the tensor
print("Shape of the tensor:", mat.shape)

# Size of the tensor
print("Size of the tensor:", mat.size)

# Data type of the tensor
print("Data type of the tensor:", mat.dtype)

[[1 2 3]
 [4 5 6]
 [4 5 0]]
Shape of the tensor: (3, 3)
Size of the tensor: 9
Data type of the tensor: int32


In [14]:
tensor_3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print("\n3D Tensor:")
print(tensor_3d)

print("Dimension of the 3D tensor:", tensor_3d.ndim)
print("Shape of the 3D tensor:", tensor_3d.shape)
print("Size of the 3D tensor:", tensor_3d.size)
print("Data type of the 3D tensor:", tensor_3d.dtype)


3D Tensor:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension of the 3D tensor: 3
Shape of the 3D tensor: (2, 3, 2)
Size of the 3D tensor: 12
Data type of the 3D tensor: int32


In [16]:
tensor_5d = np.array([[[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]],[[[[17,18],[19,20]],[[21,22],[23,24]]],[[[25,26],[27,28]],[[29,30],[31,32]]]]])
tensor_5d

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]],



       [[[[17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24]]],


        [[[25, 26],
          [27, 28]],

         [[29, 30],
          [31, 32]]]]])