# PyTroch
PyTorch is an open-source machine learning library developed by Facebook's AI Research lab. It is widely used for applications such as computer vision and natural language processing. PyTorch provides a flexible and dynamic computational graph, making it easy to build and train deep learning models.

In [2]:
import torch

In [3]:
x = torch.zeros(6,4)
x.dtype, x

(torch.float32,
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [5]:
i = torch.ones(6,4, dtype=torch.float32)
i

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

`torch.rand` 

In [44]:
torch.manual_seed(1337)

In [51]:
torch.rand(6,4, dtype=torch.float32)

tensor([[0.9553, 0.3789, 0.8534, 0.0675],
        [0.4318, 0.2314, 0.7686, 0.5905],
        [0.9349, 0.0279, 0.3925, 0.6079],
        [0.7329, 0.6789, 0.3100, 0.9123],
        [0.3307, 0.8773, 0.0139, 0.9370],
        [0.9902, 0.1232, 0.8713, 0.6281]])

# Automatic Differentiation Engine 
example of RNN 

In [53]:
x = torch.randn(1,10)
prev_h = torch.randn(1,20)
W_h = torch.randn(20,20)
W_x = torch.randn(20,10)

i2h = torch.mm(W_x , x.t())
h2h = torch.mm(W_h, prev_h.t())
next_h = i2h + h2h 
next_h = next_h.tanh()

loss = next_h.sum()

Explanation of above model in short: 
x is the input tensor (1,10) and h is the hidden state tensor (1,20). The RNN takes these inputs and produces an output tensor (1,20) and an updated hidden state tensor (1,20). The output tensor represents the predictions made by the RNN based on the input data, while the hidden state tensor captures the internal memory of the RNN that is used to make future predictions.

dimensions : x is 1,10 because it represents a single sequence of length 10, while h is 1,20 because it represents the hidden state of the RNN, which has a size of 20. The output tensor is also 1,20 because it represents the predictions made by the RNN based on the input data and the hidden state.

# A simple model

In [55]:
import torch.nn as nn 
import torch.nn.functional as F

In [56]:
class LeNet(nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()

        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)

        self.fe1 = nn.Linear(16*6*6, 120)
        self.fe2 = nn.Linear(120, 84)
        self.fe3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1 , self.num_flat_features(x))
        x = F.relu(self.fe1(x))
        x = F.relu(self.fe2(x))
        x = self.fe3(x)
        return x 

    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [57]:
net = LeNet()
print(net)

LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fe1): Linear(in_features=576, out_features=120, bias=True)
  (fe2): Linear(in_features=120, out_features=84, bias=True)
  (fe3): Linear(in_features=84, out_features=10, bias=True)
)


In [58]:
input = torch.randn(1,1,32,32)
print(net(input))


tensor([[-0.0459,  0.0437,  0.0744, -0.0505, -0.1102,  0.0257, -0.1318, -0.0197,
         -0.0067, -0.0135]], grad_fn=<AddmmBackward0>)
