In [3]:
import torch 

class Net(torch.nn.Module):

    def __init__(self):
        super(Net,self).__init__()

        self.linear1 = torch.nn.Linear(100,200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200,10)
        self.softmax = torch.nn.Softmax(dim=1)

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)  
        x = self.linear2(x)
        x = self.softmax(x)

        return x 


In [11]:
net = Net()

print(net)
# print(net.linear1.bias, net.linear1.weight)
print(net.linear1.children)
print(net.linear2)

Net(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)
<bound method Module.children of Linear(in_features=100, out_features=200, bias=True)>
Linear(in_features=200, out_features=10, bias=True)


In [14]:
for param in net.parameters():
    print(param)
    print(param.shape)

Parameter containing:
tensor([[ 0.0752, -0.0250,  0.0797,  ..., -0.0482,  0.0410,  0.0948],
        [ 0.0129,  0.0156,  0.0467,  ..., -0.0203, -0.0579, -0.0114],
        [-0.0580, -0.0482, -0.0332,  ..., -0.0910, -0.0674, -0.0490],
        ...,
        [-0.0805,  0.0855,  0.0168,  ...,  0.0759,  0.0187,  0.0191],
        [-0.0885, -0.0151, -0.0250,  ...,  0.0474, -0.0619,  0.0550],
        [ 0.0405, -0.0930, -0.0217,  ...,  0.0429, -0.0825,  0.0583]],
       requires_grad=True)
torch.Size([200, 100])
Parameter containing:
tensor([-0.0783,  0.0841, -0.0577,  0.0952,  0.0859,  0.0100,  0.0218, -0.0134,
         0.0591,  0.0004,  0.0680,  0.0843, -0.0666,  0.0203,  0.0948, -0.0944,
        -0.0472,  0.0758, -0.0957, -0.0118,  0.0243,  0.0454, -0.0587,  0.0956,
         0.0377, -0.0965, -0.0591,  0.0537, -0.0543,  0.0675,  0.0821, -0.0486,
        -0.0193,  0.0768,  0.0586, -0.0295,  0.0628,  0.0337, -0.0749,  0.0431,
         0.0178, -0.0629, -0.0955,  0.0583, -0.0105, -0.0089,  0.0928,  

# Linear Layers

In [17]:
lin = torch.nn.Linear(3,2)
x = torch.rand(1,3)

print(x)
print(lin(x))

for param in lin.parameters():
    print(param)
    print(param.shape)



tensor([[0.3457, 0.3402, 0.5815]])
tensor([[-0.5355,  0.2964]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.5029, -0.3267,  0.5521],
        [-0.1875,  0.3324,  0.4742]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([-0.5715, -0.0276], requires_grad=True)
torch.Size([2])



* nn.ReLU is an Object/Module. It acts like a structural building block.
* F.relu (from torch.nn.functional) is a Pure Function. It acts like a raw mathematical operator.

------------------------------
## 1. nn.ReLU (The Object/Layer Approach)
When you use nn.ReLU, you are creating a Python object (an instance of a class). Because it is an object, it can be dropped into structural containers like nn.Sequential.
How you use it:

```python
import torch.nn as nn
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # You define it as a structural layer in __init__
        self.layer1 = nn.Linear(10, 20)
        self.relu = nn.ReLU() 

    def forward(self, x):
        # You call it like a layer in forward
        x = self.layer1(x)
        x = self.relu(x)
        return x
```

* Best for: Clean, structured code or when building models using nn.Sequential.

------------------------------
## 2. F.relu (The Function Approach)
When you use F.relu, you are calling a raw function directly. It doesn't hold any state, it doesn't need to be initialized in __init__, and you just import it and use it right inside the forward pass.
How you use it:
```python
import torch.nn as nnimport torch.nn.functional as F
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # No ReLU defined here! Only layers with learnable weights.
        self.layer1 = nn.Linear(10, 20)

    def forward(self, x):
        # You apply it directly like a math function
        x = self.layer1(x)
        x = F.relu(x) 
        return x
```

* Best for: Quick operations, avoiding clutter in your __init__, and activations that don't have any weights to learn.

------------------------------
## The Golden Rule of Thumb: Do they have weights?
Activations like ReLU, Softmax, Sigmoid, and Tanh do not have any learnable weights (parameters). They just take a number and change it based on a formula. Because they have no weights, using F.relu or nn.ReLU makes absolutely zero difference to your model's performance or training. It is purely a matter of personal coding style.
However, for layers that do have weights—like nn.Linear (Linear/Dense layers) or nn.Conv2d (Convolutional layers)—you must use the nn object version in __init__ so PyTorch knows to track and update those weights during backpropagation.


