In [1]:
import torch 
import torch.nn as nn 


In [2]:
# transform = transforms.Compose(
#     [transforms.ToTensor(),
#      transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

# trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
#                                         download=True, transform=transform)
# trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
#                                           shuffle=True, num_workers=2)

# testset = torchvision.datasets.CIFAR10(root='./data', train=False,
#                                        download=True, transform=transform)
# testloader = torch.utils.data.DataLoader(testset, batch_size=4,
#                                          shuffle=False, num_workers=2)

# classes = ('plane', 'car', 'bird', 'cat',
#            'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

you create a net = Net() 

then a loss criterion = nn.CrossEntropyLoss() 

then an optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9) 

then you can create a training loop like this:



In [13]:
# 1D : (X)
print(torch.randn(5))

#2D : (rows, cols) or (height, width) or (batch size, features)
print(torch.randn(2, 3))

# 3D : (depth, height, width) or (channels, height, width)
# NLP and time series
print(torch.randn(3, 2, 3))

#4D : (batch size, channels, height, width) 
print(torch.randn(2, 3, 2, 2))
# batch of 2 images, 3 channels, 8x8 pixels each ; every channel becomes a 2d matrix. 

#5D : (batch size, channels, depth, height, width) or (batch, time, channels, height, width)
# used in video or 3D data. 

tensor([ 0.3792,  0.1124,  1.2337,  0.6418, -0.6884])
tensor([[-1.7305, -2.1073, -0.2731],
        [-0.5434,  0.4118, -0.5510]])
tensor([[[ 0.1364, -0.3955,  0.8002],
         [-0.6497,  1.9556,  0.8954]],

        [[ 0.1375,  1.0365, -0.8140],
         [ 0.1752,  0.3667,  0.0808]],

        [[-1.0907, -0.5466,  1.2159],
         [-0.1829, -1.4381,  0.3807]]])
tensor([[[[ 0.5100, -0.6395],
          [ 0.5121, -0.4085]],

         [[ 1.1043,  0.4778],
          [-0.6250, -1.6906]],

         [[ 0.1244, -0.9549],
          [-0.3736, -0.0956]]],


        [[[ 0.1857, -1.1694],
          [ 1.1880, -0.2523]],

         [[-0.5356,  1.8993],
          [ 1.1121, -0.6368]],

         [[-0.4237,  1.5170],
          [ 0.9043, -0.6109]]]])


In [4]:
x = torch.randn(1, 3, 2,2)

x

tensor([[[[-0.3707,  0.1879],
          [ 0.0530,  1.0687]],

         [[ 0.2068, -1.8624],
          [ 0.8412, -0.5586]],

         [[-1.4484,  0.2569],
          [ 0.7700,  0.1261]]]])

In [22]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d
old_id , id(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.6673, 0.2734],
        [0.7980, 0.6920]])


(2185939380912, 2185939380912)

In [23]:
torch.cuda.is_available()

True

In [25]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)
print(c)

d = c.squeeze(0)
print(d.shape)
print(d)

torch.Size([1, 20])
tensor([[0.2598, 0.4452, 0.5068, 0.0316, 0.4149, 0.3394, 0.4378, 0.1397, 0.9102,
         0.2367, 0.1290, 0.9538, 0.0921, 0.8906, 0.9819, 0.7900, 0.2186, 0.8143,
         0.8218, 0.2577]])
torch.Size([20])
tensor([0.2598, 0.4452, 0.5068, 0.0316, 0.4149, 0.3394, 0.4378, 0.1397, 0.9102,
        0.2367, 0.1290, 0.9538, 0.0921, 0.8906, 0.9819, 0.7900, 0.2186, 0.8143,
        0.8218, 0.2577])
torch.Size([2, 2])
tensor([[0.8941, 0.6974],
        [0.6535, 0.5856]])
torch.Size([2, 2])
tensor([[0.8941, 0.6974],
        [0.6535, 0.5856]])



## The Golden Rule

* unsqueeze(): Adds a dimension of size 1. (Makes the tensor more complex/nested).
* squeeze(): Removes dimensions of size 1. (Flattens out unnecessary single-item dimensions).

------------------------------
## 1. unsqueeze(dim): Adding a Dimension
You use unsqueeze when a PyTorch model expects a specific number of dimensions, but your data is missing one. The dim parameter specifies where to insert the new dimension.
Imagine you have a 1D tensor representing 3 features:

x = torch.tensor([10, 20, 30])  # Shape: torch.Size([3]) (1D)

By unsqueezing at different positions, you change its structural meaning:

* x.unsqueeze(0) → Shape: torch.Size([1, 3]) (2D)
* What it means: It turns a list into a matrix with 1 row and 3 columns. (Commonly used to add a mock "Batch Size" of 1).
* x.unsqueeze(1) → Shape: torch.Size([3, 1]) (2D)
* What it means: It turns a list into a matrix with 3 rows and 1 column.

------------------------------
## 2. squeeze(): Removing Dimensions
If you have dimensions of size 1 that you don't need anymore, squeeze() drops them entirely.
Imagine you have a tensor with an annoying shape from an image batch extraction:

y = torch.randn(1, 3, 1, 32)  # Shape: torch.Size([1, 3, 1, 32])


* y.squeeze() (No arguments)
* Result: Shape becomes torch.Size([3, 32]).
   * What happened: PyTorch automatically looked for all dimensions that equal 1 and deleted them.
* y.squeeze(0) (Specific dimension)
* Result: Shape becomes torch.Size([3, 1, 32]).
   * What happened: It only removed the 0th dimension because it was size 1.
* y.squeeze(1) (Safe check)
* Result: Shape stays torch.Size([1, 3, 1, 32]).
   * What happened: Nothing! Dimension 1 has a size of 3, so PyTorch safely ignores it. squeeze() never crushes data greater than 1.


